version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloudresumechallenge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j7sxiadjw2rc"
s3_prefix = "cloudresumechallenge"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

